// Code generated by Kitex v0.16.3. DO NOT EDIT.

package spiff

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
	spiffpb "spiff/internal/grpcserver/kitex_gen/spiffpb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Upload(ctx context.Context, callOptions ...callopt.Option) (stream Spiff_UploadClient, err error)
	Download(ctx context.Context, Req *spiffpb.DownloadRequest, callOptions ...callopt.Option) (stream Spiff_DownloadClient, err error)
	Compare(ctx context.Context, Req *spiffpb.CompareRequest, callOptions ...callopt.Option) (r *spiffpb.CompareResponse, err error)
	Fetch(ctx context.Context, Req *spiffpb.FetchRequest, callOptions ...callopt.Option) (r *spiffpb.FetchResponse, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	Upload(ctx context.Context, callOptions ...streamcall.Option) (stream Spiff_UploadClient, err error)
	Download(ctx context.Context, Req *spiffpb.DownloadRequest, callOptions ...streamcall.Option) (stream Spiff_DownloadClient, err error)
}

type Spiff_UploadClient interface {
	streaming.Stream
	Send(*spiffpb.Chunk) error
	CloseAndRecv() (*spiffpb.UploadResponse, error)
}

type Spiff_DownloadClient interface {
	streaming.Stream
	Recv() (*spiffpb.Chunk, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kSpiffClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSpiffClient struct {
	*kClient
}

func (p *kSpiffClient) Upload(ctx context.Context, callOptions ...callopt.Option) (stream Spiff_UploadClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Upload(ctx)
}

func (p *kSpiffClient) Download(ctx context.Context, Req *spiffpb.DownloadRequest, callOptions ...callopt.Option) (stream Spiff_DownloadClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Download(ctx, Req)
}

func (p *kSpiffClient) Compare(ctx context.Context, Req *spiffpb.CompareRequest, callOptions ...callopt.Option) (r *spiffpb.CompareResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Compare(ctx, Req)
}

func (p *kSpiffClient) Fetch(ctx context.Context, Req *spiffpb.FetchRequest, callOptions ...callopt.Option) (r *spiffpb.FetchResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Fetch(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kSpiffStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kSpiffStreamClient struct {
	*kClient
}

func (p *kSpiffStreamClient) Upload(ctx context.Context, callOptions ...streamcall.Option) (stream Spiff_UploadClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.Upload(ctx)
}

func (p *kSpiffStreamClient) Download(ctx context.Context, Req *spiffpb.DownloadRequest, callOptions ...streamcall.Option) (stream Spiff_DownloadClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.Download(ctx, Req)
}
