// Code generated by Kitex v0.16.3. DO NOT EDIT.
package spiff

import (
	server "github.com/cloudwego/kitex/server"
	spiffpb "spiff/internal/grpcserver/kitex_gen/spiffpb"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler spiffpb.Spiff, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler spiffpb.Spiff, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
