// Code generated by Kitex v0.16.3. DO NOT EDIT.

package spiff

import (
	"context"
	"errors"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
	spiffpb "spiff/internal/grpcserver/kitex_gen/spiffpb"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"Upload": kitex.NewMethodInfo(
		uploadHandler,
		newUploadArgs,
		newUploadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingClient),
	),
	"Download": kitex.NewMethodInfo(
		downloadHandler,
		newDownloadArgs,
		newDownloadResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingServer),
	),
	"Compare": kitex.NewMethodInfo(
		compareHandler,
		newCompareArgs,
		newCompareResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"Fetch": kitex.NewMethodInfo(
		fetchHandler,
		newFetchArgs,
		newFetchResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	spiffServiceInfo                = NewServiceInfo()
	spiffServiceInfoForClient       = NewServiceInfoForClient()
	spiffServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return spiffServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return spiffServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return spiffServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(true, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Spiff"
	handlerType := (*spiffpb.Spiff)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "spiff",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.16.3",
		Extra:           extra,
	}
	return svcInfo
}

func uploadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &spiffUploadServer{st}
	return handler.(spiffpb.Spiff).Upload(stream)
}

type spiffUploadClient struct {
	streaming.Stream
}

func (x *spiffUploadClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *spiffUploadClient) Send(m *spiffpb.Chunk) error {
	return x.Stream.SendMsg(m)
}
func (x *spiffUploadClient) CloseAndRecv() (*spiffpb.UploadResponse, error) {
	if err := x.Stream.Close(); err != nil {
		return nil, err
	}
	m := new(spiffpb.UploadResponse)
	return m, x.Stream.RecvMsg(m)
}

type spiffUploadServer struct {
	streaming.Stream
}

func (x *spiffUploadServer) SendAndClose(m *spiffpb.UploadResponse) error {
	return x.Stream.SendMsg(m)
}

func (x *spiffUploadServer) Recv() (*spiffpb.Chunk, error) {
	m := new(spiffpb.Chunk)
	return m, x.Stream.RecvMsg(m)
}

func newUploadArgs() interface{} {
	return &UploadArgs{}
}

func newUploadResult() interface{} {
	return &UploadResult{}
}

type UploadArgs struct {
	Req *spiffpb.Chunk
}

func (p *UploadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *UploadArgs) Unmarshal(in []byte) error {
	msg := new(spiffpb.Chunk)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var UploadArgs_Req_DEFAULT *spiffpb.Chunk

func (p *UploadArgs) GetReq() *spiffpb.Chunk {
	if !p.IsSetReq() {
		return UploadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *UploadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UploadArgs) GetFirstArgument() interface{} {
	return p.Req
}

type UploadResult struct {
	Success *spiffpb.UploadResponse
}

var UploadResult_Success_DEFAULT *spiffpb.UploadResponse

func (p *UploadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *UploadResult) Unmarshal(in []byte) error {
	msg := new(spiffpb.UploadResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *UploadResult) GetSuccess() *spiffpb.UploadResponse {
	if !p.IsSetSuccess() {
		return UploadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *UploadResult) SetSuccess(x interface{}) {
	p.Success = x.(*spiffpb.UploadResponse)
}

func (p *UploadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UploadResult) GetResult() interface{} {
	return p.Success
}

func downloadHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	streamingArgs, ok := arg.(*streaming.Args)
	if !ok {
		return errInvalidMessageType
	}
	st := streamingArgs.Stream
	stream := &spiffDownloadServer{st}
	req := new(spiffpb.DownloadRequest)
	if err := st.RecvMsg(req); err != nil {
		return err
	}
	return handler.(spiffpb.Spiff).Download(req, stream)
}

type spiffDownloadClient struct {
	streaming.Stream
}

func (x *spiffDownloadClient) DoFinish(err error) {
	if finisher, ok := x.Stream.(streaming.WithDoFinish); ok {
		finisher.DoFinish(err)
	} else {
		panic(fmt.Sprintf("streaming.WithDoFinish is not implemented by %T", x.Stream))
	}
}
func (x *spiffDownloadClient) Recv() (*spiffpb.Chunk, error) {
	m := new(spiffpb.Chunk)
	return m, x.Stream.RecvMsg(m)
}

type spiffDownloadServer struct {
	streaming.Stream
}

func (x *spiffDownloadServer) Send(m *spiffpb.Chunk) error {
	return x.Stream.SendMsg(m)
}

func newDownloadArgs() interface{} {
	return &DownloadArgs{}
}

func newDownloadResult() interface{} {
	return &DownloadResult{}
}

type DownloadArgs struct {
	Req *spiffpb.DownloadRequest
}

func (p *DownloadArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *DownloadArgs) Unmarshal(in []byte) error {
	msg := new(spiffpb.DownloadRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DownloadArgs_Req_DEFAULT *spiffpb.DownloadRequest

func (p *DownloadArgs) GetReq() *spiffpb.DownloadRequest {
	if !p.IsSetReq() {
		return DownloadArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DownloadArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *DownloadArgs) GetFirstArgument() interface{} {
	return p.Req
}

type DownloadResult struct {
	Success *spiffpb.Chunk
}

var DownloadResult_Success_DEFAULT *spiffpb.Chunk

func (p *DownloadResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *DownloadResult) Unmarshal(in []byte) error {
	msg := new(spiffpb.Chunk)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DownloadResult) GetSuccess() *spiffpb.Chunk {
	if !p.IsSetSuccess() {
		return DownloadResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DownloadResult) SetSuccess(x interface{}) {
	p.Success = x.(*spiffpb.Chunk)
}

func (p *DownloadResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *DownloadResult) GetResult() interface{} {
	return p.Success
}

func compareHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(spiffpb.CompareRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(spiffpb.Spiff).Compare(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *CompareArgs:
		success, err := handler.(spiffpb.Spiff).Compare(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*CompareResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newCompareArgs() interface{} {
	return &CompareArgs{}
}

func newCompareResult() interface{} {
	return &CompareResult{}
}

type CompareArgs struct {
	Req *spiffpb.CompareRequest
}

func (p *CompareArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *CompareArgs) Unmarshal(in []byte) error {
	msg := new(spiffpb.CompareRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var CompareArgs_Req_DEFAULT *spiffpb.CompareRequest

func (p *CompareArgs) GetReq() *spiffpb.CompareRequest {
	if !p.IsSetReq() {
		return CompareArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *CompareArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CompareArgs) GetFirstArgument() interface{} {
	return p.Req
}

type CompareResult struct {
	Success *spiffpb.CompareResponse
}

var CompareResult_Success_DEFAULT *spiffpb.CompareResponse

func (p *CompareResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *CompareResult) Unmarshal(in []byte) error {
	msg := new(spiffpb.CompareResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *CompareResult) GetSuccess() *spiffpb.CompareResponse {
	if !p.IsSetSuccess() {
		return CompareResult_Success_DEFAULT
	}
	return p.Success
}

func (p *CompareResult) SetSuccess(x interface{}) {
	p.Success = x.(*spiffpb.CompareResponse)
}

func (p *CompareResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CompareResult) GetResult() interface{} {
	return p.Success
}

func fetchHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(spiffpb.FetchRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(spiffpb.Spiff).Fetch(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *FetchArgs:
		success, err := handler.(spiffpb.Spiff).Fetch(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FetchResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newFetchArgs() interface{} {
	return &FetchArgs{}
}

func newFetchResult() interface{} {
	return &FetchResult{}
}

type FetchArgs struct {
	Req *spiffpb.FetchRequest
}

func (p *FetchArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *FetchArgs) Unmarshal(in []byte) error {
	msg := new(spiffpb.FetchRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FetchArgs_Req_DEFAULT *spiffpb.FetchRequest

func (p *FetchArgs) GetReq() *spiffpb.FetchRequest {
	if !p.IsSetReq() {
		return FetchArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FetchArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *FetchArgs) GetFirstArgument() interface{} {
	return p.Req
}

type FetchResult struct {
	Success *spiffpb.FetchResponse
}

var FetchResult_Success_DEFAULT *spiffpb.FetchResponse

func (p *FetchResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *FetchResult) Unmarshal(in []byte) error {
	msg := new(spiffpb.FetchResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FetchResult) GetSuccess() *spiffpb.FetchResponse {
	if !p.IsSetSuccess() {
		return FetchResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FetchResult) SetSuccess(x interface{}) {
	p.Success = x.(*spiffpb.FetchResponse)
}

func (p *FetchResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *FetchResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Upload(ctx context.Context) (Spiff_UploadClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Upload", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &spiffUploadClient{res.Stream}
	return stream, nil
}

func (p *kClient) Download(ctx context.Context, req *spiffpb.DownloadRequest) (Spiff_DownloadClient, error) {
	streamClient, ok := p.c.(client.Streaming)
	if !ok {
		return nil, fmt.Errorf("client not support streaming")
	}
	res := new(streaming.Result)
	err := streamClient.Stream(ctx, "Download", nil, res)
	if err != nil {
		return nil, err
	}
	stream := &spiffDownloadClient{res.Stream}

	if err := stream.Stream.SendMsg(req); err != nil {
		return nil, err
	}
	if err := stream.Stream.Close(); err != nil {
		return nil, err
	}
	return stream, nil
}

func (p *kClient) Compare(ctx context.Context, Req *spiffpb.CompareRequest) (r *spiffpb.CompareResponse, err error) {
	var _args CompareArgs
	_args.Req = Req
	var _result CompareResult
	if err = p.c.Call(ctx, "Compare", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Fetch(ctx context.Context, Req *spiffpb.FetchRequest) (r *spiffpb.FetchResponse, err error) {
	var _args FetchArgs
	_args.Req = Req
	var _result FetchResult
	if err = p.c.Call(ctx, "Fetch", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
