// Code generated by Kitex v0.16.3. DO NOT EDIT.

package spiffpb

import (
	"context"

	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/prutal"
)

type Chunk struct {
	Data []byte `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (x *Chunk) Reset() { *x = Chunk{} }

func (x *Chunk) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *Chunk) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *Chunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (x *UploadResponse) Reset() { *x = UploadResponse{} }

func (x *UploadResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *UploadResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *UploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DownloadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (x *DownloadRequest) Reset() { *x = DownloadRequest{} }

func (x *DownloadRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *DownloadRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *DownloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CompareRequest struct {
	LeftId  string `protobuf:"bytes,1,opt,name=left_id" json:"left_id,omitempty"`
	RightId string `protobuf:"bytes,2,opt,name=right_id" json:"right_id,omitempty"`
}

func (x *CompareRequest) Reset() { *x = CompareRequest{} }

func (x *CompareRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CompareRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CompareRequest) GetLeftId() string {
	if x != nil {
		return x.LeftId
	}
	return ""
}

func (x *CompareRequest) GetRightId() string {
	if x != nil {
		return x.RightId
	}
	return ""
}

type CompareResponse struct {
	Diff string `protobuf:"bytes,1,opt,name=diff" json:"diff,omitempty"`
}

func (x *CompareResponse) Reset() { *x = CompareResponse{} }

func (x *CompareResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *CompareResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *CompareResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

type FetchRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (x *FetchRequest) Reset() { *x = FetchRequest{} }

func (x *FetchRequest) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FetchRequest) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FetchResponse struct {
	Html []byte `protobuf:"bytes,1,opt,name=html" json:"html,omitempty"`
}

func (x *FetchResponse) Reset() { *x = FetchResponse{} }

func (x *FetchResponse) Marshal(in []byte) ([]byte, error) { return prutal.MarshalAppend(in, x) }

func (x *FetchResponse) Unmarshal(in []byte) error { return prutal.Unmarshal(in, x) }

func (x *FetchResponse) GetHtml() []byte {
	if x != nil {
		return x.Html
	}
	return nil
}

type Spiff interface {
	Upload(stream Spiff_UploadServer) (err error)
	Download(req *DownloadRequest, stream Spiff_DownloadServer) (err error)
	Compare(ctx context.Context, req *CompareRequest) (res *CompareResponse, err error)
	Fetch(ctx context.Context, req *FetchRequest) (res *FetchResponse, err error)
}

type Spiff_UploadServer interface {
	streaming.Stream
	Recv() (*Chunk, error)
	SendAndClose(*UploadResponse) error
}

type Spiff_DownloadServer interface {
	streaming.Stream
	Send(*Chunk) error
}
